#!/bin/bash
projPath=$(dirname $0 | xargs realpath | xargs dirname | xargs dirname)
checkStatus() {
  cd "${projPath}/$1"
  res=$(git status)
  [[ $res == *"working tree clean"* ]] && echo -e "${app} \xE2\x9C\x94\n-----\n" || echo -e "${app} $(git status --porcelain)\n-----\n"
}
syncToRemote() {
  cd "${projPath}/$1"
  res=$(git --no-pager log origin/main..HEAD)
  [[ -z $res ]] && echo "✅" && return 0 || echo -e "$res"
}
for app in $(ls $projPath); do
  [[ -d "${projPath}/${app}/.git" ]] && checkStatus $app
done
