#!/bin/bash
opsRoot=$(realpath $0 | xargs dirname | xargs dirname)
appsRoot=$(dirname $opsRoot)

killExistingContainer() {
  tmux kill-session -t "$1"
}

runContainer() {
  svc="$1"
  cmd="$2"
  session="service-$1"
  [[ ! -z $(tmux ls | grep "service-$1") ]] && killExistingContainer "$session"
  tmux new-session -d -s "$session";
  tmux send "cd $appsRoot/$svc; npm run $cmd" ENTER
}

startServiceInContainer() {
  [[ -z $1 ]] && echo -e "No service name provided" && return 1
  echo -e "Starting $1 in container"
  runner=""
  pkgJSON=$(cat "$appsRoot/$1/package.json")
  [[ $(echo $pkgJSON | jq '.scripts."service:watch"') != "null" ]] && runner="service:watch"
  [[ $(echo $pkgJSON | jq '.scripts.dev') != "null" ]] && runner="dev"
  [[ -z $runner ]] && echo -e "No valid runner script registered in ${svc}" && return 1
  runContainer "$1" "$runner"
  return 0
}
startAllServicesInContainer() {
  echo -e "Starting all services"
  for svc in $(ls $appsRoot); do
    [[ -d "$appsRoot/$svc" ]] && [[ -f "$appsRoot/$svc/configs.json" ]] && startServiceInContainer "$svc"
  done
}

[[ ! -z $1 ]] && startServiceInContainer $1 && exit $?
startAllServicesInContainer