#!/bin/zsh
projPath=$(dirname $0 | xargs realpath | xargs dirname | xargs dirname)
syncToRemote() {
  cd "${projPath}/$1"
  res=$(git --no-pager log origin/main..HEAD --pretty='%s [%h]' | tr '\n' ' \: ' | awk '{$1=$1};1')
  count=$(git --no-pager log origin/main..HEAD --pretty='%s [%h]' | awk '{$1=$1};1' | wc -l)
  count=$(echo $count | awk '{$1=$1};1')
  [[ $count -eq 1 ]] && suffix='' || suffix='s'
  [[ -z $res ]] && echo -e "$1 - \xE2\x9C\x94" && return 0
  echo -e "$1 - ${count} unpushed commit${suffix}\n. Pushing them to remote"
  git push origin main
}
echo -e "[$(date '+%Y-%m-%dT%T')]\nChecking for unpushed changes"
for app in $(ls $projPath); do
  [[ -d "${projPath}/${app}/.git" ]] && syncToRemote $app
done