#!/bin/bash
projPath=$(dirname $0 | xargs realpath | xargs dirname | xargs dirname)
serviceStatus() {
  [[ ! -d "$projPath/$1" ]] && echo -e "Service path $1 not found" && exit 1
  config="${projPath}/$1/configs.json"
  port=$(cat $config | jq '.app.port')
  _pid=$(lsof -i ":${port}" | grep -v "PID" | awk '{print $2}' | uniq | tr '\n' ' ' | sed 's/ $//g')
  [[ -z $_pid ]] && echo -e "$1 is not running" && return 0 || echo -e "$1 is listening on port $port [PID: $_pid]"
}

[[ ! -z $1 ]] && serviceStatus $1 ||
for app in $(ls $projPath); do
  [[ -f "${projPath}/${app}/configs.json" ]] && serviceStatus $app
done