#!/bin/bash
projPath=$(dirname $0 | xargs realpath | xargs dirname | xargs dirname)
serviceStatus() {
  [[ ! -d "$projPath/$1" ]] && echo -e "Service path $1 not found" && exit 1
  config="${projPath}/$1/configs.json"
  port=$(cat $config | jq '.app.port')
  _pid=$(lsof -i ":${port}" | grep -v "PID" | awk '{print $2}' | uniq | tr '\n' ' ' | sed 's/ $//g')
  [[ -z $_pid ]] && echo -e "$1 [✗ | Port: $port]" && return 0 || echo -e "$1 [\xE2\x9C\x94 | Port: $port | PID: $_pid]"
}

[[ ! -z $1 ]] && serviceStatus $1 && exit 0 || echo -e "[$(date '+%Y-%m-%dT%T')] Service [Status | Port | PID]" &&
for app in $(ls $projPath); do
  [[ -f "${projPath}/${app}/configs.json" ]] && serviceStatus $app
done