#!/bin/bash
projPath=$(dirname $0 | xargs realpath | xargs dirname | xargs dirname)
utilsRoot="$projPath/utils"
cd $utilsRoot
hash=$(git --no-pager log -1 --pretty='%s [%h]')
message="Upgrades novostack-utils - $hash"

unstashIfNeeded() {
  app=$1
  stashed=$2
  [[ $stashed == 1 ]] && cd $projPath/$app && git stash pop && cd $projPath && return 0 || echo -e "No changes stashed on $app." && return 0
}

checkStatus() {
  app=$1
  cd $projPath/$app
  [[ $(git stash) == *"No local changes"* ]] && stashed=0 || stashed=1
  [[ $(git --no-pager log --pretty='%s [%h]') == *"$hash"* ]] && echo "$app is updated" && unstashIfNeeded $app $stashed && return 0 || echo -e "Updating $app" && npm update && git add package*json && git commit -m "$message" && git push origin main && unstashIfNeeded $app $stashed && return 0
}

cd $projPath
for app in $(ls $projPath); do
  [[ -d $projPath/$app ]] && [[ -d $projPath/$app/.git ]] && [[ -f $projPath/$app/configs.json ]] && [[ $(cat $projPath/$app/package.json | jq '.dependencies | ."novostack-utils"') != "null" ]] && checkStatus $app
done